fix(constraints): make constraints --fix persist changes to manifest
yarnpkg/berry pull request #2245
Opened 2020-12-16 18:18 UTC by bgotink

**What's the problem this PR addresses?**

The change introduced in #1775 to fix fixing the field constraints
broke fixing dependency constraints, by overriding the changes made
to the manifest before persisting.

Fixes #2242

**How did you fix it?**

Dependency constraints work on the Manifest, field constraints work on the raw JSON object. Sync the two after every execution of the constraints to ensure every iteration uses the correct values.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2020-12-16 18:27 UTC, merceyz requested changes
We should have some tests to ensure we don't regress on this in the future (granted I should have added some for #1775 but oh well)

2020-12-18 12:14 UTC, bgotink commented on packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
> +} = require(`pkg-tests-core`);
I've replaced these with xfs

I copied the `constraints` test file to start from, and I'm sure a lot of tests are created by copying an existing test file. If existing tests aren't updated to use xfs, I'd expect a lot of these kind of comments to pop up.

There are even test files that use both xfs and this `fs` import in the same test.

2020-12-18 12:27 UTC, merceyz approved these changes
Looks good :+1:

2020-12-19 01:19 UTC, merged

2020-12-21 14:05 UTC, merceyz commented
This seems to introduce a different bug, when a fix is applied the content of array fields are duplicated