fix: make patchfile path relative to prefixPath
yarnpkg/berry pull request #2466
Opened 2021-02-11 05:39 UTC by charlessuh

**What's the problem this PR addresses?**

In my project (which is using PnP and strict mode), I have `package-a` listed as a dependency, and `package-a` lists as a dependency `patch:package-b@1.0.0#./package-c.patch`.

When I attempt to do `yarn install` the top level, I get the error `ENOENT: no such file or directory, open './package-c.patch`.

...

**How did you fix it?**

I'm not super familiar with the yarn code, but it appears that the `patchFiles` function is ignoring the `prefixPath` property.

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2021-02-11 08:56 UTC, merceyz requested changes
Thanks for looking into this :+1: 
Could you add a test to https://github.com/yarnpkg/berry/blob/c428aeea8ca3400e4c3a46cf1fbddfdbf81874aa/packages/acceptance-tests/pkg-tests-specs/sources/protocols/patch.test.js so we can ensure we don't regress on this?

2021-02-11 08:56 UTC, merceyz commented on .yarn/versions/d2fb9e75.yml
> +  "@yarnpkg/builder": patch
Only need a patch release on `@yarnpkg/cli` and `@yarnpkg/plugin-patch`

2021-02-13 01:06 UTC, charlessuh commented
> Thanks for looking into this 👍
> Could you add a test to https://github.com/yarnpkg/berry/blob/c428aeea8ca3400e4c3a46cf1fbddfdbf81874aa/packages/acceptance-tests/pkg-tests-specs/sources/protocols/patch.test.js so we can ensure we don't regress on this?

Okay, I've taken a stab at creating a test that fails but now passing with this PR.

2021-02-13 12:59 UTC, merceyz commented on packages/acceptance-tests/pkg-tests-specs/sources/protocols/patch.test.js
> +      `it should apply a patch when package is virtual`,
```suggestion
      `it should apply patches relative to the package`,
```

2021-02-13 12:59 UTC, merceyz approved these changes

2021-02-13 20:30 UTC, merged

2021-02-13 20:30 UTC, arcanis commented
Thanks, @charlessuh !