Adds an extension for NextAuth.js
yarnpkg/berry pull request #2493
Opened 2021-02-20 17:01 UTC by simnalamburt

**What's the problem this PR addresses?**
NextAuth.js is not usable with Yarn 2 PnP due to wrong dependency. I tried to patch NextAuth.js first but they rejected it. So I'm fixing Next.js and Yarn instead. I already have fixed the Next.js side and this is the remaining piece.

**How did you fix it?**
Added an extension

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

###### References
- https://github.com/nextauthjs/next-auth/pull/1034
- https://github.com/vercel/next.js/pull/20971

2021-02-20 17:39 UTC, merceyz requested changes
As we mentioned in the linked issues it was a problem with how Next.js provided the polyfill for `process` so adding it as a dependency to `next-auth` isn't the correct fix, do you have a repro that shows that it's still needed so it can be fixed in Next.js?

I tested with https://github.com/nextauthjs/next-auth-example but can't reproduce it

2021-02-20 17:51 UTC, simnalamburt commented
As I stated in https://github.com/vercel/next.js/pull/20971#issuecomment-778262016, it's not yet.

How to reproduce the issue:

```
git clone https://github.com/simnalamburt/next-auth-example.git
cd next-auth-example
yarn
yarn dev
```

![image](https://user-images.githubusercontent.com/4435445/108604143-5a0b4c80-73ef-11eb-871e-985daf3482a0.png)

###### Reference
- https://github.com/simnalamburt/next-auth-example

2021-02-20 18:01 UTC, JakubKoralewski commented
I can't repro it either anymore. I just checked with my project in which I originally found the problem where a week ago I needed this to fix the `Module not found: can't resolve 'process'` error:
```yml
packageExtensions:
  next-auth@*:
    dependencies:
      process: "^0.11.10"
```
but now I removed it, tested it (first it failed), but after updating next-auth to `"next-auth": "^3.3.0",` from `"next-auth": "^3.2.0-canary.35",` I get an error different than `Module not found: can't resolve 'process'`. I think this is fixed! @simnalamburt, could you check again  with latest next-auth?

2021-02-20 19:17 UTC, simnalamburt commented
The error reproduction above is using the latest version of next and next-auth.

###### Reference
- https://github.com/simnalamburt/next-auth-example/blob/c384f8ae906227bdbb11bed92bc4774a0ceb1899/yarn.lock#L2222

2021-02-20 19:18 UTC, merceyz commented
> It fails when you use it with Webpack 5.

Yeah that makes it a missing polyfill in Next.js, see https://github.com/vercel/next.js/issues/22247 and https://github.com/vercel/next.js/blob/fea5c18132146976913f4148210b74d6d9b1ef8c/packages/next/build/webpack-config.ts#L394-L398

2021-02-20 19:18 UTC, closed without merging

2021-02-20 19:33 UTC, simnalamburt commented
Does adding `process:require.resolve('process')` to the polyfill list actually solves this issue? It didn't worked for me.

###### Reference
- https://github.com/vercel/next.js/issues/22247#issuecomment-782737356
- simnalamburt/next-auth-example@c128495

2021-02-20 19:41 UTC, merceyz commented
You need to use `require.resolve('process/')` otherwise it will just return `process` again

2021-03-02 03:11 UTC, simnalamburt commented
Currently there's no known solution or workaround of https://github.com/vercel/next.js/issues/22247, shall we reopen this PR?