Support PnP with Neovim native LSP
yarnpkg/berry pull request #3041
Opened 2021-06-21 14:43 UTC by tapayne88

Linked to https://github.com/theia-ide/typescript-language-server/pull/220

**What's the problem this PR addresses?**
Neovim's native LSP client uses [theia-ide/typescript-language-server](https://github.com/theia-ide/typescript-language-server) to wrap `tsserver`. For go-to-definition to work yarn needs to resolve virtual filepaths to on-disk paths for neovim to open.

**How did you fix it?**
Followed example of how the issues was fixed for other editor implementations
https://github.com/yarnpkg/berry/pull/2598

**Checklist**

- [ ] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ ] I have set the packages that need to be released for my changes to be effective.

- [ ] I will check that all automated PR checks pass before the PR gets reviewed.

2021-06-23 14:49 UTC, tapayne88 commented
Following advice of neovim core team I've updated the URI scheme to be something other than `zipfile` which already has a plugin handling it. New scheme will allow a new plugin to parse URI encoded path and open `zipfile` compatible URI
https://github.com/neovim/neovim/issues/14867#issuecomment-865228662

2021-06-23 14:58 UTC, merceyz commented
Why not format the path so it works with `zipfile:` (`vim-rzip`)?

2021-06-24 10:29 UTC, tapayne88 commented
> Why not format the path so it works with `zipfile:` (`vim-rzip`)?

Unfortunately [theia-ide/typescript-language-server](https://github.com/theia-ide/typescript-language-server) URI parses (and encodes) the file paths it's passed. This means the file paths aren't in a format vim-rzip can handle (`:` becomes `%3A` etc.). It does this for regular `file://` scheme too so didn't want to split the behaviour.

In the case of neovim there is some special handling in the core for URIs with `file://` scheme which URI decodes them when they arrive from the LSP (before opening). This doesn't happen for any other URI schemes and isn't considered core behaviour, it should be handled by a plugin.

I guess we have a couple of options
- submit a PR to vim-rzip to URI decode the URIs it handles
- create a new plugin to handle URI decoding of `yarnpnp:` schemes

2021-06-24 10:34 UTC, merceyz commented
If the `.replace(/\.zip\//, '.zip::')` part is what breaks it you can remove that, it's only there for `coc-nvim`

2021-06-24 10:52 UTC, tapayne88 commented
There are other characters like `@` which get encoded and break it. I'm pretty sure we need the `::` as I think that's part of how vim-rzip handles the file

2021-07-01 11:31 UTC, arcanis commented
I'm not sure I completely understand the diff - where does this `yarnpnp:` protocol comes from? If it's additional configuration to set, perhaps it should be added to the [SDK documentation](https://yarnpkg.com/getting-started/editor-sdks#vim--cocnvim) as well?

Also, couldn't we use `zipfile:` if we were to just call encodeURIComponent on the path?

2021-07-01 13:46 UTC, tapayne88 commented
Yeah, I'm not entirely comfortable with it but not sure what's best tbh. I do think it would be helpful to expand the SDK documentation too.

This is the flow of LSP requests from neovim to `tsserver`.
```
neovim ---> TypeScript Language Server ---> Yarn SDK ---> tsserver
```

I don't think `encodeURIComponent` would help as the yarn SDK is the wrong side of the typescript language server to help.

Neovim core only wants to have URI decoding for `file:` scheme URIs, anything else should be handled by a plugin. There is already a plugin vim-rzip which handles `zipfile:` scheme URIs but it doesn't currently know anything about URIs or URI encoding / decoding, but it could hence the 2 options above.

> - submit a PR to vim-rzip to URI decode the URIs it handles
> - create a new plugin to handle URI decoding of yarnpnp: schemes

2021-07-09 15:35 UTC, tapayne88 commented
So after chatting with the author of vim-rzip it should be possible to use the `zipfile` scheme with this vimscript block

```vim
function! ParseURI(uri)
    return substitute(a:uri, '%\([a-fA-F0-9][a-fA-F0-9]\)', '\=nr2char("0x" . submatch(1))', "g")
endfunction

function! RzipOverride()
    autocmd! zip BufReadCmd zipfile:*,zipfile:*/*
    exe "au! zip BufReadCmd ".g:zipPlugin_ext

    autocmd zip BufReadCmd zipfile:*,zipfile:*/* exe "keepalt file " . fnameescape(ParseURI(expand("<amatch>")))
    autocmd zip BufReadCmd zipfile:*,zipfile:*/* call rzip#Read(ParseURI(expand('<amatch>')), 1)
    exe "au zip BufReadCmd ".g:zipPlugin_ext." call rzip#Browse(ParseURI(expand('<amatch>')))"
endfunction

autocmd VimEnter * call RzipOverride()
```

2021-07-16 10:06 UTC, tapayne88 commented
A slightly more refined version of the above snippet to get vim-rzip working with encoded URIs. Handles a few more edge cases but not perfect.
```vim
function! ParseURI(uri)
    return substitute(a:uri, '%\([a-fA-F0-9][a-fA-F0-9]\)', '\=nr2char("0x" . submatch(1))', "g")
endfunction

function! RzipOverride()
    autocmd! zip BufReadCmd   zipfile:*/*
    exe "au! zip BufReadCmd ".g:zipPlugin_ext
    autocmd zip BufReadCmd   zipfile:*/*
                \ if ParseURI(expand("<amatch>")) !=# expand("<amatch>") |
                \     sil! exe "bwipeout " . fnameescape(ParseURI(expand("<amatch>"))) |
                \     exe "keepalt file " . fnameescape(ParseURI(expand("<amatch>"))) |
                \     sil! exe "bwipeout " . fnameescape(expand("<amatch>")) |
                \ endif
    autocmd zip BufReadCmd   zipfile:*/* call rzip#Read(ParseURI(expand("<amatch>")), 1)
    exe "au zip BufReadCmd ".g:zipPlugin_ext." call rzip#Browse(ParseURI(expand('<amatch>')))"
endfunction

autocmd VimEnter * call RzipOverride()
```

I think I'm happy this PR has the change needed to support neovim's native LSP and Yarn PnP.

@arcanis / @merceyz would you be able to advise how I can get this over the line? I've made a stab at flagging the packages for release but not sure I'm correct

2021-07-16 10:24 UTC, merceyz requested changes
Fantastic, could you add some documentation for Neovim to https://github.com/yarnpkg/berry/blob/ed66dcd58e285819191f592b2aefbccd13ba5aa6/packages/gatsby/content/getting-started/editor-sdks.md?

> I've made a stab at flagging the packages for release but not sure I'm correct

It's correct 👍

2021-07-16 10:49 UTC, tapayne88 commented
> Fantastic, could you add some documentation for Neovim to https://github.com/yarnpkg/berry/blob/ed66dcd58e285819191f592b2aefbccd13ba5aa6/packages/gatsby/content/getting-started/editor-sdks.md?
> 
> > I've made a stab at flagging the packages for release but not sure I'm correct
> 
> It's correct 👍

Brill, will do!

2021-07-16 17:43 UTC, merceyz commented
If the snippet in https://github.com/yarnpkg/berry/pull/3041#issuecomment-881333138 is required that should be documented as well

2021-07-18 09:35 UTC, merged

2021-07-18 09:35 UTC, arcanis commented
Thanks!