fix(ZipOpenFS): handle .zip in the middle of file name
yarnpkg/berry pull request #3042
Opened 2021-06-22 14:32 UTC by ratson

**What's the problem this PR addresses?**

Path with `.zip` in the middle of the file name is not extracted correctly.

Closes https://github.com/yarnpkg/berry/issues/2975

**How did you fix it?**

Added 2 edge cases to the test.

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ ] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2021-06-22 14:45 UTC, merceyz commented
For context that function was added in https://github.com/yarnpkg/berry/pull/2796 to speed up installs / replace this regex
```regex
.*?(?<!\/)\.zip(?=\/|$)
```
We need to verify that this fix doesn't regress the performance to the point where we could just use the regex

2021-06-22 14:57 UTC, ratson commented
@merceyz 
code block 1 is new code, 
code block 2 is regex version, 

Before:
https://jsben.ch/CTkgN
![Screenshot 2021-06-22 at 22-55-08 JSBEN CH Benchmarking for JavaScript -](https://user-images.githubusercontent.com/2682937/122947808-06187080-d3ad-11eb-98cf-f26a629f558c.png)

After:
https://jsben.ch/b07Zt
![Screenshot 2021-06-22 at 22-54-03 JSBEN CH Benchmarking for JavaScript -](https://user-images.githubusercontent.com/2682937/122947825-087aca80-d3ad-11eb-898d-0b5f024b42ff.png)

2021-06-22 18:02 UTC, merceyz requested changes
Should be updated to handle an "unlimited" amount of `.zip` occurrences in a filename

2021-06-23 16:18 UTC, ratson commented
@merceyz Which test case is in your mind? The change should have handled multiple `.zip` occurrences.

2021-06-23 16:43 UTC, merceyz reviewed
It's an edge case but here is a failing test case

2021-06-23 16:43 UTC, merceyz commented on packages/yarnpkg-fslib/tests/ZipOpenFS.test.ts
> +    [`./a/b/c/foo.zip-bar.zip/bar/baz/qux.zip`, `./a/b/c/foo.zip-bar.zip`],
```suggestion
    [`./a/b/c/foo.zip-bar.zip/bar/baz/qux.zip`, `./a/b/c/foo.zip-bar.zip`],
    [`./a/b/c/foo.zip-bar/foo.zip-bar/foo.zip-bar.zip/d`, `./a/b/c/foo.zip-bar/foo.zip-bar/foo.zip-bar.zip`],
```

2021-06-24 13:41 UTC, ratson commented
https://jsben.ch/oBqKF
![Screenshot 2021-06-24 at 21-41-00 JSBEN CH Benchmarking for JavaScript -](https://user-images.githubusercontent.com/2682937/123273054-e2803200-d534-11eb-93c0-fe60808d8279.png)

2021-07-18 09:00 UTC, merged