Improvements to `yarn init` / `yarn set version`
yarnpkg/berry pull request #3066
Opened 2021-06-30 14:08 UTC by arcanis

**What's the problem this PR addresses?**

This commit improves the workflows around `yarn init` and `yarn set version` in various ways:

- It's now possible to run `yarn init` on a folder that already exists. It'll simply add the missing baseline files and fields.
- Running `yarn init` will set the `packageManager` field from Corepack.
- Similarly, `yarn set version` will set the field, and `yarn set version from sources` will remove it.
- If Yarn detects that `yarnPath` points to the same binary content as the current one, it'll ignore it.
- The URLs used for `yarn set version` now come from our own website (cached behind Cloudflare).
- If operating within Corepack, the shims we add to the environment will point to it (rather than the current binary).

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2021-06-30 16:55 UTC, merceyz commented on packages/plugin-init/sources/commands/init.ts
> +  // Deprecated; doesn't have any effect anymore, but we can't removing it for
```suggestion
  // Deprecated; doesn't have any effect anymore, but we can't remove it for
```

2021-06-30 17:00 UTC, merceyz requested changes
Running in an empty directory with `-i` crashes with the following error
```
$ yarn init -i
➤ YN0000: Downloading https://repo.yarnpkg.com/2.4.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-2.4.2.cjs
➤ YN0000: Done in 0s 343ms

Usage Error: A package.json already exists in the specified directory

$ yarn init [-p,--private] [-w,--workspace] [-i,--install]
```

2021-06-30 20:34 UTC, paul-soporan commented on packages/plugin-init/sources/commands/init.ts
> +  // good for removal in 4.x.
Can you turn this into a `TODO` so that it comes up when searching for `TODO`s in the codebase?

2021-07-01 10:35 UTC, arcanis commented
> Running in an empty directory with `-i` crashes with the following error

It's because this diff makes the `-i` process incompatible with what the prior Yarn releases expect to find when running init (so for example `yarn init -i=2.4.1` would break too). Since `-i` is `-i=latest`, it'll be solved once `latest` becomes the formal 3.0.0.

2021-07-01 17:50 UTC, merceyz commented
I see, I can see that's not what it does but I expected it to do the init itself then install the version specified, not install the specified version then use it to init. 🤔

2021-07-01 17:57 UTC, merceyz approved these changes

2021-07-05 10:05 UTC, merged