feat(plugin-pack): reload manifest after prepack script
yarnpkg/berry pull request #3146
Opened 2021-07-20 14:26 UTC by kherock

**What's the problem this PR addresses?**

Resolves #3145 - see issue for rationale.

**How did you fix it?**

This unconditionally reloads the active workspace's manifest during `prepareForPack`.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2021-07-20 14:51 UTC, arcanis requested changes
That won't work. We special-case `package.json` precisely because we want to use the manifest from memory, because `beforeWorkspacePacking` is meant to allow in-memory package mutations (which we use to implement `publishConfig`).

Generally, `prepack` is intended to be idempotent, so mutating the `package.json` isn't a practice we'd recommend. Instead, you should use `beforeWorkspacePacking` (which is more verbose). It's a bit unclear by your issue what you mean by "I want to Yarn to still perform the processing it normally does", so I'm not sure why it wouldn't work.

2021-07-20 15:03 UTC, kherock commented
Just to be clear, this isn't at odds with what `beforeWorkspacePacking`. I also wouldn't advise mutating package.json, but I think disallowing it altogether is unfair especially since this flow works just fine with npm (and I believe Yarn classic).

> It's a bit unclear by your issue what you mean by "I want to Yarn to still perform the processing it normally does"
I want Yarn and its plugins to still run their `beforeWorkspacePacking` _after_ the updated package.json is loaded. There's the built-in one that validates and replaces `workspace:` protocols, but I also don't want to interfere with any other hooks. If I were to write my own `beforeWorkspacePacking`, I'd need a way to ensure that my hook runs first.

2021-08-12 03:27 UTC, kherock commented
@arcanis @merceyz Just bumping this one last time for a second opinion. I'm not really sure how else to really solve this short of patching the Yarn CLI with every release 😕. Intuitively, I'd expect that `yarn run prepack && yarn pack` would generate the same archive as a single run as `yarn pack`.

2021-08-12 14:34 UTC, arcanis commented
Yep, that looks good to me - I've updated the versions since I think it qualifies as a bugfix more than a breaking change.

2021-08-12 14:34 UTC, arcanis approved these changes

2021-08-17 08:30 UTC, arcanis approved these changes

2021-08-17 08:30 UTC, merged