feat: add support for `workspace:~` and `workspace:^` aliases
yarnpkg/berry pull request #3250
Opened 2021-08-08 12:02 UTC by colinaaa

**What's the problem this PR addresses?**

closes #2658 

...

**How did you fix it?**

accept new alias in `@yarnpkg/core` and resolve to correct version in `@yarnpkg/plugin-pack`

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2021-08-08 12:05 UTC, merceyz commented on .yarn/versions/7c4f7995.yml
> +  "@yarnpkg/plugin-pack": patch
```suggestion
  "@yarnpkg/core": minor
  "@yarnpkg/plugin-pack": minor
```

2021-08-08 19:33 UTC, paul-soporan requested changes
Thanks for the contribution! Can you also add a test for `yarn pack` [here](https://github.com/yarnpkg/berry/blob/01586a88806a2bebd7edb28d1bee3581b1fd3762/packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js#L327-L368)?

2021-08-08 19:33 UTC, paul-soporan commented on .yarn/versions/7c4f7995.yml
> +
`@yarnpkg/cli` needs a `minor` release too since these changes affect the CLI.

2021-08-08 19:33 UTC, paul-soporan commented on packages/plugin-pack/sources/index.ts
> +        // For workspace:~ and workspace:^ we add selector in front of workspace version
```suggestion
        // For workspace:~ and workspace:^ we add the selector in front of the workspace version
```

2021-08-08 19:33 UTC, paul-soporan commented on packages/plugin-pack/sources/index.ts
> +          versionToWrite =  `${range.selector}${matchingWorkspace.manifest.version}`;
(Same fallback as in the `if` above)
```suggestion
          versionToWrite =  `${range.selector}${matchingWorkspace.manifest.version ?? `0.0.0`}`;
```

2021-08-09 17:31 UTC, paul-soporan approved these changes

2021-08-09 17:41 UTC, merceyz requested changes
Implementation and tests looks good but this needs to be documented

https://github.com/yarnpkg/berry/blob/9c7fd34b85fec4db70e0074d27e5e14aeb8b7a78/packages/gatsby/content/features/workspaces.md#publishing-workspaces

2021-08-12 09:46 UTC, merged

2021-08-12 09:47 UTC, arcanis commented
Thanks!