fix(nm): Reinstall removed modules directories
yarnpkg/berry pull request #3467
Opened 2021-09-21 14:37 UTC by larixer

**What's the problem this PR addresses?**

When you remove unplugged directory with pnp linker, it reinstalls the directory again. This behaviour is currently different for the nm linker, it will perform reinstall only when top-level nm folder is removed. The PR changes this for the nm linker, so that both linkers behave the same - when you remove directory deep inside `node_modules` the nm linker reinstalls only this directory and rebuilds the module if needed. The same logic applies to the bin symlinks - removed bin symlinks gets recreated by the nm linker.

**How did you fix it?**

I use the fact that the nm linker writes `node_modules/.yarn-state.yml` as the last operation of the link step, hence it must have the `mtime` which is greater than all the files and folders inside `node_modules`. To detect whether the user has removed any module directory inside `node_modules`, it is enough to check whether each parent `node_modules` folder has `mtime >= state_file_mtime` and if it does - the user has modified the directory, we then perform `readdir`  and find entries deleted by the user, if any, and record these modifications in the preinstall state. The algorithm that diffs install and preinstall state later does the rest of the job of reinstall deleted modules and directories.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2021-09-21 14:53 UTC, larixer commented
Babel E2E test passing depends on #3438

2022-03-21 20:11 UTC, penx commented
@arcanis @merceyz is there anything that can be done to get this in? 🙏

2022-03-22 11:07 UTC, merceyz requested changes

2022-03-22 11:38 UTC, larixer commented on packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
> +  it(`should reinstall and rebuild dependencies deleted by the user on the next install`,
@merceyz Thanks! Yes, indeed, its a duplicate, removed

2022-03-22 14:43 UTC, merceyz approved these changes

2022-03-22 23:57 UTC, merged