Sync `yarn init -2` with docs
yarnpkg/berry pull request #4035
Opened 2022-01-30 13:00 UTC by tebeco

**What's the problem this PR addresses?**
The current status of the docs and the generated result of `yarn init -2` missmatch:
![image](https://user-images.githubusercontent.com/2266487/151700656-b3ce7c92-701e-419a-aed5-c2e955e88d58.png)

After asking on the `Yarn Discord server` It was suggested to sync `yarn init` as the docs would the right version of it

**How did you fix it?**

* Asked before on discord
* was suggested to PR it here
* Remove the leading `/` on missmatch
* Add by default `!.yarn/versions` 

**Checklist**
- [ ] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [ ] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2022-01-30 14:51 UTC, paul-soporan requested changes

2022-01-30 14:51 UTC, paul-soporan commented on packages/plugin-init/sources/commands/init.ts
> +        `!.yarn/version`,
```suggestion
        `!.yarn/versions`,
```

2022-01-30 16:57 UTC, paul-soporan approved these changes

2022-01-30 17:06 UTC, merceyz approved these changes

2022-01-31 18:16 UTC, tebeco commented
I'm not exactly sure why that would be a bug only on windows ?
flack test ? I do not have the "re-run workflow" available 
=> empty commit

2022-01-31 18:22 UTC, merceyz commented
It's a flaky test, no need to force push to re-run it as it's likely to fail again, we'll merge without the CI passing if we need to.

2022-01-31 18:23 UTC, tebeco commented
do I have anything left to do ? (want to try a rebase anyway ?)

2022-01-31 18:27 UTC, merceyz commented
Nope, without a passing CI we'll have to wait for @arcanis to force merge it.

2022-01-31 18:49 UTC, merged