Don't use corepack when packing git dependencies
yarnpkg/berry pull request #4175
Opened 2022-03-03 05:48 UTC by charlessuh

**What's the problem this PR addresses?**

The `prepareExternalProject` function (which us used to pack git dependencies) is written under the assumption that it launches another instance of the same version of yarn that is currently running. However, the `makeScriptEnv` function, when running under corepack, will now launch another corepack instance of yarn (which may then launch a different version of yarn depending on the current working directory.)

This causes differences in behavior between yarn installed via corepack and yarn installed via npm, potentially resulting in different checksums and cause failures with the default behavior of `checksumBehavior: throw`.

One case which is problematic is if the git dependency does not have a `packageManager` field in its `package.json`, as corepack yarn will read the `package.json` and pack using v1, while non-corepack yarn will pack using whatever the currently running version of yarn is (berry.)

...

**How did you fix it?**

`makeScriptEnv` accepts an additional argument to determine if corepack should be used or not. Alternative proposals are welcome.

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2022-03-03 07:55 UTC, charlessuh commented
On second thought, I wonder if this should be reversed -- keep the behavior of corepack yarn, and change the behavior of non-corepack yarn.

2022-03-03 10:07 UTC, charlessuh commented
@merceyz: What do you think about this PR instead? Using corepack here seems pretty complicated.

2022-03-22 23:49 UTC, merceyz requested changes
We can't disable the use of corepack here as the target project might be using it.

2022-03-24 01:37 UTC, charlessuh commented
> We can't disable the use of corepack here as the target project might be using it.

Well, that's the behavior of non-corepack yarn, correct? In other words, if you are using non-corepack yarn, it will ignore whatever version of yarn was specified in the git dependency's `package.json` for packing and checksumming purposes.

I guess the question is, do we want non-corepack yarn and corepack yarn to behave the same here, at least until non-corepack is no longer supported?

2022-03-29 19:57 UTC, closed without merging