WIP feat: expose preferReuse and preferCached
yarnpkg/berry pull request #4221
Opened 2022-03-15 11:40 UTC by marionebl

**What's the problem this PR addresses?**

In some of my projects I want to keep dependencies across all workspaces in sync as much as possible; collaborating with a larger number of developers on those repositories for me means that often `preferInteractive` is not enough to make developers reuse existing versions. `--cached` fits the bill but there is no option to enable it by default.

...

**How did you fix it?**

* Added a `preferCached` option
* Added a `preferReuse` options

...

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [ ] I have set the packages that need to be released for my changes to be effective.
- [ ] I will check that all automated PR checks pass before the PR gets reviewed.

2022-03-31 00:08 UTC, merceyz requested changes
Thanks for the PR, I really appreciate that you included a test and updated the JSON schema.
I have a few comments but otherwise this looks good.

2022-03-31 00:08 UTC, merceyz commented on packages/plugin-essentials/sources/commands/add.ts
> +    ].filter(isStrategy);
```suggestion
    ].filter((strategy): strategy is suggestUtils.Strategy => typeof strategy !== `undefined`);
```
I would prefer to have this inlined here

2022-03-31 00:08 UTC, merceyz commented on packages/plugin-essentials/sources/commands/add.ts
> +
```suggestion
```

2022-03-31 09:23 UTC, merceyz requested changes

2022-03-31 09:23 UTC, merceyz commented on packages/plugin-essentials/sources/index.ts
> +      description: `If true, the CLI will use the hightest version of existing, latest for new dependencies`,
```suggestion
      description: `If true, `yarn add` will attempt to reuse the most common dependency range in other workspaces.`,
```

2022-04-08 08:16 UTC, merged

2022-04-08 08:16 UTC, arcanis commented
LGTM! Thanks @marionebl!