fix(dedupe): fix dedupe error when alias in dependency tree
yarnpkg/berry pull request #4241
Opened 2022-03-18 02:25 UTC by mchill

**What's the problem this PR addresses?**

`yarn dedupe` fails in certain cases when npm aliases are present in the dependency tree.

The bug was ultimately caused by the dedupe algorithm relying on identHash to be a unique identifier of an installed package. However, the descriptors of aliases stored in `project.storedDescriptors` contain the identHash of the alias name, not the resolved package. This meant dedupe chose candidates that didn't exist for aliased packages.

Fixes #4226

**How did you fix it?**

I added a function that attempts to fetch the identHash of a package from the list of originalPackages if possible, since the identHash stored there refers to the resolved package.

**Checklist**

- [ ] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ ] I have set the packages that need to be released for my changes to be effective.

- [ ] I will check that all automated PR checks pass before the PR gets reviewed.

2022-03-18 11:16 UTC, merceyz requested changes

2022-03-18 12:44 UTC, mchill commented on packages/plugin-essentials/sources/dedupeUtils.ts
> +  return (project.originalPackages.get(project.storedResolutions.get(descriptor.descriptorHash)!) || descriptor).identHash;
No problem! It now throws an error on failing to find the storedResolution, but not the originalPackage, to keep in line with the existing functionality.

2022-04-18 15:56 UTC, mchill commented
@merceyz At some point in the last month, another change fixed https://github.com/yarnpkg/berry/issues/4226. I removed all of my changes except the test, which would still be nice to get merged to avoid a regression.

2022-07-12 12:36 UTC, merceyz approved these changes
It was fixed by https://github.com/yarnpkg/berry/pull/4302 but more tests is always nice.

2022-07-12 12:36 UTC, merged