Uses exclusively Corepack by default
yarnpkg/berry pull request #4254
Opened 2022-03-22 22:40 UTC by arcanis

**What's the problem this PR addresses?**

Node 14 will soon be the new Node LTS. Since it ships with Corepack, we don't need to store the version file unless users already expect really want it.

**How did you fix it?**

The new code detects whether there's a `yarnPath` setting. If there is, it assumes that the version file will be needed. Otherwise, it just updates the `packageManager` field.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2022-03-23 14:03 UTC, merceyz commented
If there is no `yarnPath` value already present, how would you force Yarn to set it?

2022-03-24 12:41 UTC, arcanis commented
> If there is no `yarnPath` value already present, how would you force Yarn to set it?

I've added a `--yarn-path` setting that will forcibly set `yarnPath`.

2022-03-24 19:00 UTC, merceyz requested changes

2022-03-24 19:00 UTC, merceyz commented on packages/plugin-essentials/sources/commands/set/version.ts
> +  });
We should default this to true if the user doesn't have Corepack enabled (`process.env.COREPACK_ROOT`)

2022-03-28 08:31 UTC, merceyz requested changes
Needs tests

2022-03-29 07:34 UTC, ylemkimon commented
If Corepack is not enabled (which is by default), wouldn't this make Yarn classic (1.x) come into action? I think it should create a stub/placeholder binary to let people know to enable Corepack for the time being, and ignore it in binary comparison.

2022-03-29 09:37 UTC, arcanis commented
> If Corepack is not enabled (which is by default), wouldn't this make Yarn classic (1.x) come into action?

The PR title isn't accurate at the moment; Yarn will *prefer* using exclusively Corepack when possible, but if it isn't enabled (COREPACK_ROOT isn't in the environment) it'll fallback on `yarnPath`.

2022-03-29 09:42 UTC, ylemkimon commented
I was thinking of situations where a project created on an environment with Corepack enabled (hence no `yarnPath`) is shared with environments with Corepack disabled.

2022-03-29 09:57 UTC, arcanis commented
Yes, in that situation it won't work in the current state. To address that I'm considering adding Corepack support to the Yarn 1.x distribution (but only for the `yarn` binary, of course), so that any of `corepack enable` / `npm install -g yarn` would be as if Corepack was installed.

2022-03-29 15:20 UTC, merged