Improves boot time
yarnpkg/berry pull request #4261
Opened 2022-03-24 12:32 UTC by arcanis

**What's the problem this PR addresses?**

Yarn is currently a little slow to start. Even a `yarn --version` takes ~280ms on my (slow) machine.

**How did you fix it?**

~~This diff implements bundle splitting by adding a `--split` option to the bundle generator that, when used, causes it to emit a self-extracting file that unpacks the chunks on disk then runs them. In practice it isn't more performant, so it's unlikely to be enabled by default, but having this capability can be useful for experimentation purposes.~~

~~A few other runtime speed improvements not directly related to it are also implemented.~~

- Reimplemented Tinylogic using Pegjs rather than Chevrotine
- Changed some of the `got` import into type imports
- Removed `yup` from the modules exposed to plugins (was legacy)

```sh
YARN_IGNORE_PATH=1 hyperfine -w 1 "node ./master.cjs --version" "node ./after.cjs --version"
Benchmark 1: node ./master.cjs --version
  Time (mean ± σ):     214.8 ms ±   1.1 ms    [User: 228.5 ms, System: 18.1 ms]
  Range (min … max):   213.4 ms … 216.9 ms    13 runs

Benchmark 2: node ./after.cjs --version
  Time (mean ± σ):     178.0 ms ±   1.3 ms    [User: 189.2 ms, System: 20.0 ms]
  Range (min … max):   175.7 ms … 180.8 ms    16 runs

Summary
  'node ./after.cjs --version' ran
    1.21 ± 0.01 times faster than 'node ./master.cjs --version'
```

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2022-03-24 12:49 UTC, merceyz requested changes

2022-03-24 14:39 UTC, arcanis commented on packages/yarnpkg-libzip/sources/sync.ts
> +  return asyncLibzip;
The sync version isn't used apart from our tests, so I'd expect it to be tree-shaken; I'll double-check that it isn't included twice

2022-03-24 14:41 UTC, arcanis commented on packages/yarnpkg-builder/sources/commands/build/bundle.ts
> +  });
Fair enough, I mostly added it to enable further experimentations, but I'm fine with reverting it. Worst case it'll still be available as a standalone commit in this original PR 😄

2022-03-24 15:17 UTC, arcanis commented on packages/yarnpkg-libzip/sources/sync.ts
> +  return asyncLibzip;
It wasn't tree shaken; reverted this file

2022-03-24 18:55 UTC, merceyz requested changes
> Moved the builtin patch behind lazy imports
Moved the worker hook behind a lazy import
Moved the PnP hook behind a lazy import

Without bundle splitting these can be reverted as they are just functions

2022-03-24 18:55 UTC, merceyz commented on packages/yarnpkg-cli/sources/tools/backportClipanionCompatibility.ts
> -export function backportClipanionCompatibility(clipanion: any) {
Removing this file belongs in https://github.com/yarnpkg/berry/pull/4262

2022-03-24 18:56 UTC, merceyz commented on packages/yarnpkg-cli/sources/tools/getPluginConfiguration.val.js
> +    return `    [${JSON.stringify(require(`${request}/package.json`).name)}, _${index}],\n`;
Ref https://github.com/yarnpkg/berry/pull/4262

2022-03-25 17:30 UTC, merceyz approved these changes

2022-03-26 14:42 UTC, merceyz approved these changes

2022-03-26 14:42 UTC, merged