Set version home check
yarnpkg/berry pull request #4664
Opened 2022-07-25 20:45 UTC by JoshuaKGoldberg

**What's the problem this PR addresses?**
Users should be blocked from accidentally running `yarn set version` from the home directory (`~`). This adds an error to that case unless a new `--skip-home-check` is specified.

Resolves #4426.

**How did you fix it?**
Checks `this.context.cwd` against [`homedir()`](https://nodejs.org/api/os.html#oshomedir) at the beginning of the `execute()` method.

I'm not confident I answered correctly on the version updates. 🤷 

**Testing**: I couldn't find any unit tests for `version.ts`, and it seems risky to run acceptance tests in the user's home directory. Is there a testing strategy this PR should go with? Help please?

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

Co-authored-by: @nikstern <nik@codecademy.com>

2022-07-25 22:05 UTC, merceyz requested changes
This seems like treating the symptom and not the underlying cause, in the issue you wrote that `yarn set version classic` didn't work as expected, we should be looking into that instead.

> I couldn't find any unit tests for version.ts

They are integration tests in this case, you can find them here: https://github.com/yarnpkg/berry/blob/15c481dce19f1a7e56b875b96f11c9ef67dc4c2d/packages/acceptance-tests/pkg-tests-specs/sources/commands/set/version.test.ts

> it seems risky to run acceptance tests in the user's home directory

You can set the home directory as an environment variable in the test.
Example from the terminal:
```console
$ HOME="foo" node -p "require('os').homedir()"
foo
```

2022-09-16 08:17 UTC, dylanh724 commented
As mentioned [here](https://github.com/yarnpkg/berry/issues/4426), tackling the issue is ideal - but it's also been months since this was reported with many folks repro'ing this issue (and will continue doing so) until fixed. 

I push to please let this workaround pass so we can code in peace and without error until the main issue is resolved.

2022-09-16 09:27 UTC, arcanis commented
> until fixed (by perhaps 2023?)

Please learn how to interact professionally on open-source repositories. Being snarky makes me less likely to care about whatever problem *you* have and *I* don't have. Don't abuse our will to help.

The problem is also wider than this codebase; the global Yarn is supposed to be Yarn 1.x, so running `yarn set version` from the home folder will lead to code being evaluated by Yarn 1, ie a different codebase. This PR alone won't fix the root issue.

2022-09-24 15:59 UTC, closed without merging

2023-06-13 00:34 UTC, JasonPei-Medibank commented
I ran into the same issue with even the latest version (3.6.0), any updates on this? 
I'm using macOS Ventura

2023-06-13 00:36 UTC, withinoneyear commented
I ran into the same issue with even the latest version (3.6.0), any updates on this? 
I'm using macOS Ventura