fix(fslib): handle file path buffers
yarnpkg/berry pull request #4907
Opened 2022-09-26 18:52 UTC by rotu

**What's the problem this PR addresses?**
Resolves https://github.com/yarnpkg/berry/issues/1818

I was getting build errors similar to the below. This is because yarn assumes every filesystem path is provided as a string, but Node's internal version of `rimraf` allows them to be buffers.

```
Executing task: yarn run build 

vite v3.1.3 building for production...
✓ 42 modules transformed.
p.replace is not a function

[vite:dts] Start generate declaration files...
[vite:dts] Declaration files built in 1275ms.

error during build:
TypeError: p.replace is not a function
    at Object.toPortablePath (C:\Users\dan\Source\vue-maplibre-gl\.pnp.cjs:3194:9)
    at PosixFS.mapToBase (C:\Users\dan\Source\vue-maplibre-gl\.pnp.cjs:5765:18)
    at PosixFS.rmdirSync (C:\Users\dan\Source\vue-maplibre-gl\.pnp.cjs:5676:39)
    at URLFS.rmdirSync (C:\Users\dan\Source\vue-maplibre-gl\.pnp.cjs:5676:24)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
```

**How did you fix it?**
I made the `NativePath` type admit `Buffer`s, and ensure that these buffers are stringified as part of the conversion to `PortablePath`. Note that paths are assumed to be UTF8, which is a similar restriction as https://nodejs.org/api/fs.html#fspromisesrealpathpath-options

...

**Checklist**

- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [X] I have set the packages that need to be released for my changes to be effective.

- [X] I will check that all automated PR checks pass before the PR gets reviewed.

2022-09-26 20:38 UTC, merceyz requested changes
See https://github.com/yarnpkg/berry/pull/4215#pullrequestreview-918088183

2022-10-04 17:41 UTC, adalinesimonian commented
Looking forward to this fix as it is blocking builds for my org. If you need a hand, I'm happy to help push this forward by addressing the requested changes; otherwise, looking forward to the updates.

2022-10-04 17:54 UTC, arcanis commented
It's definitely one of our higher-priority issues; we've been lucky to have people from the community looking at this (thanks @rotu and @CharlesStover!), but we're not convinced changing `toPortablePath` is the right strategy. I think the best way would probably something like:

- Renaming [`URLFS`](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-fslib/sources/URLFS.ts) into something like `NodePathFS`
- Add support to `NodePathFS` for turning `Buffer` into strings
- Reject any `Buffer` that doesn't safely convert to utf8 (we won't support them for now, as they should be very rare)

This would scope the changes to a single file (plus tests), which is less risky and doesn't increase a lot the complexity (since this piece of code is already tasked from ensuring compatibility with whatever Node throws at the FakeFS API).

2022-10-04 18:53 UTC, rotu commented
@arcanis I would very much like someone to take this over. I don't know what I'm doing.

I think it's acceptable to only support paths in UTF-8. Node does: https://nodejs.org/api/fs.html#fspromisesrealpathpath-options

2022-10-04 18:59 UTC, paul-soporan commented
I can open a PR myself tomorrow addressing everything if needed (I'm the one who originally looked into supporting Buffers and we've also recently restarted discussions around this internally and arrived to a good enough solution; thank you all for reminding us about this important issue!).

> I think it's acceptable to only support paths in UTF-8. Node does: [nodejs.org/api/fs.html#fspromisesrealpathpath-options](https://nodejs.org/api/fs.html#fspromisesrealpathpath-options)

That restriction only exists for `realpath`, other functions will happily accept non-utf8 buffers and they can't be safely converted to strings without losing the encoding, they have to be kept as buffers until the end (when they're passed back to Node).

![image](https://user-images.githubusercontent.com/32596136/193903375-f035c5d9-c1b1-4326-9b33-e65b5795b49b.png)

2022-10-07 10:19 UTC, closed without merging