ci: remove outdated workflow
yarnpkg/berry pull request #4960
Opened 2022-10-13 13:01 UTC by jj811208

**What's the problem this PR addresses?**

related https://github.com/yarnpkg/berry/pull/4954

remove outdated workflow

### e2e-snowpack-workflow

snowpack is no longer actively maintained. https://www.snowpack.dev/

![image](https://user-images.githubusercontent.com/25342059/195352682-b2f4a9f5-c864-492a-b242-4160c060f19b.png)

---

### e2e-vue-cli-workflow

vue cli is in Maintenance Mode(it mean no new features will be added, only serious and common-case bugs will be fixed), and vue official is recommended to use create-vue (vite) to build vue projects. https://cli.vuejs.org/

![image](https://user-images.githubusercontent.com/25342059/195357281-484b8c9d-db35-4488-8e7b-678f11713a72.png)

---

### package-workflow

This is a workflow that is no longer used

see: https://github.com/yarnpkg/berry/pull/4954#issuecomment-1275380434

...

**How did you fix it?**

1. delete `e2e-snowpack-workflow`
2. delete `e2e-vue-cli-workflow`
3. revert https://github.com/yarnpkg/berry/pull/379 and remove something about it

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2022-10-13 13:42 UTC, arcanis commented on scripts/release/03-release-npm.sh
> -cp "$REPO_DIR"/scripts/dist-scripts/* "$TEMP_DIR"/bin
That shouldn't be removed

2022-10-13 14:09 UTC, jj811208 commented on scripts/release/03-release-npm.sh
> -cp "$REPO_DIR"/scripts/dist-scripts/* "$TEMP_DIR"/bin
OK~ I dropped this commit

2022-10-13 14:17 UTC, RDIL commented
Vue-CLI also had a case-study: https://github.com/yarnpkg/berry/issues/964

2022-10-13 14:19 UTC, RDIL commented
@Daniel15 is any of the deb packaging code used in your build infrastructure in this repo?  Just want to make sure the removal doesn't break anything.

2022-10-14 01:52 UTC, Daniel15 commented
@RDIL The only version of the Deb packaging code that's actually in use is in the v1 repo and in https://github.com/yarnpkg/release-infra

2022-10-15 16:07 UTC, RDIL approved these changes
LGTM, but should probably be looked over by others first.

2022-10-15 16:20 UTC, merceyz requested changes
The files in `scripts/dist-scripts` are still in use so those need to be restored.
Ref https://github.com/yarnpkg/berry/pull/4960#discussion_r994663027 / https://github.com/yarnpkg/berry/blob/417d119554df2f8f48b6254a58a25b17892cab15/scripts/release/03-release-npm.sh#L23

2022-10-15 18:24 UTC, jj811208 commented
> The files in `scripts/dist-scripts` are still in use so those need to be restored.

I recovered them https://github.com/yarnpkg/berry/pull/4960/commits/08b97b068feb89ce3a0218127fb20db6f2fe1aa4

but I don't quite understand the timing of their use 🥹, It looks like these files have just been copied and `chmod -x` 

https://github.com/yarnpkg/berry/blob/417d119554df2f8f48b6254a58a25b17892cab15/.github/workflows/release-candidate.yml#L63-L68

https://github.com/yarnpkg/berry/blob/417d119554df2f8f48b6254a58a25b17892cab15/scripts/release/03-release-npm.sh#L23-L24

2022-10-22 12:12 UTC, merceyz commented
> but I don't quite understand the timing of their use

They're used to create the `@yarnpkg/cli-dist` npm package for Volta.

2022-10-22 12:12 UTC, merceyz approved these changes

2022-10-22 14:40 UTC, RDIL approved these changes

2022-10-24 07:57 UTC, merged

2022-10-24 07:57 UTC, arcanis commented
Thanks @jj811208 !