fix(pnp): Use correct error code when module not found
yarnpkg/berry pull request #5355
Opened 2023-03-29 01:37 UTC by clemyan

**What's the problem this PR addresses?**

This PR makes the PnP ESM loader throw with error code `ERR_MODULE_NOT_FOUND` (instead of `MODULE_NOT_FOUND`) when a request cannot be resolved.

Closes #5334 

I am not sure about the package releases. I have marked `pnp`, `plugin-pnp` and `cli` as patch releases since other packages doesn't seem to use the ESM loader.

**How did you fix it?**

The error is thrown by the PnP CJS hook, and the ESM loader just calls the CJS hook. So we can just catch the error in the ESM loader, change the error code, and rethrow.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2023-03-29 06:58 UTC, merceyz requested changes
Thanks for the fix!

Could you add a test to https://github.com/yarnpkg/berry/blob/ca475757fe85cdc2c4b4441f6d65d38fdab230ad/packages/acceptance-tests/pkg-tests-specs/sources/pnp-esm.test.ts?

2023-03-29 18:51 UTC, clemyan commented
Added tests

2023-04-03 14:11 UTC, merceyz approved these changes

2023-04-24 19:30 UTC, merceyz requested changes

2023-04-24 19:30 UTC, merceyz commented on packages/yarnpkg-pnp/sources/esm-loader/hooks/resolve.ts
> +    }
```suggestion
    if (err instanceof Error && `code` in err && err.code === `MODULE_NOT_FOUND`) {
      err.code = `ERR_MODULE_NOT_FOUND`;
    }
    throw err;
```
We should re-throw the `error` regardless of what it is.

2023-04-24 20:41 UTC, merceyz commented on packages/yarnpkg-pnp/sources/esm-loader/hooks/resolve.ts
> +    }
I pushed the fix and added a test.

2023-04-24 20:43 UTC, merceyz approved these changes
Thanks for the fix!

2023-04-24 21:09 UTC, merged