Bumps Node requirements from 14 to 18
yarnpkg/berry pull request #5445
Opened 2023-05-16 09:05 UTC by arcanis

**What's the problem this PR addresses?**

We're still supporting Node 14, but it has reached end of life. Node 16 is still maintained, but will reach an early end of life in October, so I think it's reasonable to drop it now rather than publish a major release just for that.

**How did you fix it?**

Bumps the requirements from `14.16` to `18.12` (first LTS from the 18.x release line).

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2023-05-16 13:25 UTC, merceyz requested changes
I don't see the need of dropping support for these Node.js versions as it doesn't cost us much to keep support for them.
If that changes we can drop them and release a new major version at any point.

> rather than publish a major release just for that

It's just a number.

2023-05-16 14:06 UTC, arcanis commented
The thing is, we didn't treat it as just a number so far, and I think it's more than that in the mind of (at least a part of) the community. There's an argument to be made to change that, but it has some ramifications and I'd prefer not to rush it and repeat the kind of misunderstanding from the v2 release (in other words, that seems a post-4.0 discussion to me).

As for upgrading Node, I'm fine with keeping a loose requirement on the CLI check, but I'd prefer to avoid keeping an outdated transpilation for the sake of Node 14 users. Node 16 is perhaps another story since it has a few more months, but considering it'll quickly become unsafe (due to the OpenSSL release line [falling out of support](https://nodejs.org/en/blog/announcements/nodejs16-eol), causing Node to do the same), it could even be seen as encouraging a good practice.

2023-05-23 16:45 UTC, arcanis commented
I removed the reverts on logic updates, but kept the test runtime upgrade & `engines` field upgrade.

2023-05-23 17:36 UTC, merceyz commented
If you absolutely want to drop support for Node.js <18 and push this through we should do it fully, not half-way as that's confusing.

2023-06-01 09:24 UTC, nicolo-ribaudo commented
> For example Babel, depending on the outcome of https://github.com/babel/babel/pull/15585.

Note that we first run Yarn and then change the Node.js version, so this wouldn't affect us :) We currently use Yarn 3 even if Babel still supports Node.js 6.

2023-06-07 19:36 UTC, arcanis commented
> If you absolutely want to drop support for Node.js <18 we should do it fully, not half-way as that's confusing.

Let's do it then; since Yarn is versioned by project, it shouldn't break setups outside of upgrade attempts, which are anyone subject to other breaking changes. Worst case, if someone has a very valid use case, we'll be able to revert it without having to release a new major. I'll add back the original changes.

2023-06-16 18:57 UTC, merceyz requested changes
A few more files needs to be updated, mainly the `rollup.config.js` files, but see the list from https://github.com/yarnpkg/berry/pull/4196#pullrequestreview-902783965.

2023-06-16 18:57 UTC, merceyz commented on CHANGELOG.md
> +- With Node.js 16's End of Life [approaching fast](https://nodejs.org/en/blog/announcements/nodejs16-eol), we dropped support for both Node.js 14 and 16, with Node.js 18 being the recommended LTS ver
```suggestion
- With Node.js 16's End of Life [approaching fast](https://nodejs.org/en/blog/announcements/nodejs16-eol), we dropped support for Node.js 12, 13, 14, 15, 16, and 17, with Node.js 18 being the recommended LTS version.
```
There isn't a changelog entry for it but we also dropped support for <14.15 in https://github.com/yarnpkg/berry/pull/4196.

2023-06-22 06:42 UTC, merceyz requested changes

2023-06-22 06:42 UTC, merceyz commented on packages/yarnpkg-pnp/sources/esm-loader/loaderFlags.ts
> +export const HAS_JSON_IMPORT_ASSERTION_REQUIREMENT = major > 17 || (major === 17 && minor >= 1);
Should be able to remove these flags since they'll always be true.

2023-06-22 15:32 UTC, merceyz approved these changes
LGTM, though there is a merge conflict that needs to be resolved.

2023-06-22 22:11 UTC, merceyz commented
> Internal Error: spawn ETXTBSY
https://github.com/yarnpkg/berry/actions/runs/5350638693/jobs/9703540026?pr=5445#step:5:1067

Should be fixed in https://github.com/libuv/libuv/pull/4059 but that isn't released yet so we can either disable io_uring support by setting `UV_USE_IO_URING=0` in the environment or lock the CI to Node.js v20.2.0 until the fix is out.
I vote for the latter.

2023-06-22 23:55 UTC, paul-soporan commented on .github/workflows/integration-workflow.yml
> +        node: [18, 19, 20.2]
We should leave a comment about it.

2023-06-24 06:13 UTC, merged

2023-06-24 06:16 UTC, arcanis commented
Branch protection rules updated to the new job names