Updates the audit implementation to the bulk endpoint
yarnpkg/berry pull request #5501
Opened 2023-06-13 09:12 UTC by arcanis

**What's the problem this PR addresses?**

The current audit implementation uses the older `/audit/quick` endpoint, which has various problems. One particular is that its design requires to submit a nested payload, but since it doesn't make much sense in our case (because most of Yarn installs are flat), we flatten the package list. It causes problems when multiple packages with different versions can be found in the tree. 

Fixes #4117 
Fixes #5408

Supercedes #5409

**How did you fix it?**

This change rewrites `yarn npm audit` to use the new endpoint. As part of the migration a couple of fields are reworked (`Via` is replaced by `Dependents`, the versions are now part of a tree item rather than concatenated, we don't get the "recommendation" anymore). The options remain the same for now.

It's possible that some registries don't support the bulk endpoint. Given that it's fairly straightforward to implement, that it's been released for some time now, and that without it we would end up with an invalid `audit` implementation, I'd tend to let them deal with that.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2023-06-13 21:38 UTC, merceyz requested changes
There seems to be a bug here, no vulnerabilities are reported for `ansi-regex@4.1.0` even though [it has one](https://github.com/advisories/GHSA-93q8-gq69-wqmw).
```console
yarn add ansi-regex@4.1.0
yarn npm audit
```

2023-06-14 08:21 UTC, merceyz commented
I forgot to add the `--dev` flag to the reproduction steps, sorry about that.
```
yarn add ansi-regex@4.1.0 --dev
yarn npm audit
```

Also running an audit on this repo throws
```console
$ yarn npm audit --all --recursive
Range Error: Maximum call stack size exceeded
    at Object.stringifyIdent (/berry/packages/yarnpkg-core/sources/structUtils.ts:1:1)
    at Object.get [as stringifyIdent] (/berry/packages/yarnpkg-core/sources/structUtils.ts:15:45)      
    at Object.get [as stringifyIdent] (/berry/packages/yarnpkg-core/sources/index.ts:15:45)
    at processDescriptor (/berry/packages/plugin-npm-cli/sources/npmAuditUtils.ts:125:39)
    at processDescriptor (/berry/packages/plugin-npm-cli/sources/npmAuditUtils.ts:133:9)
    at processDescriptor (/berry/packages/plugin-npm-cli/sources/npmAuditUtils.ts:133:9)
    at processDescriptor (/berry/packages/plugin-npm-cli/sources/npmAuditUtils.ts:133:9)
    at processDescriptor (/berry/packages/plugin-npm-cli/sources/npmAuditUtils.ts:133:9)
    at processDescriptor (/berry/packages/plugin-npm-cli/sources/npmAuditUtils.ts:133:9)
    at processDescriptor (/berry/packages/plugin-npm-cli/sources/npmAuditUtils.ts:133:9)
```

2023-06-14 16:08 UTC, merceyz requested changes
Can confirm that fixes the previous reproduction however based on the the information provided in https://github.com/yarnpkg/berry/issues/3861 here is another one
```sh
corepack npm@8.19.2 init -y
corepack npm@8.19.2 install eslint@8.4.1 webpack-dev-server@3.11.3 --before 2021-12-11
corepack npm@8.19.2 audit
corepack yarn@1.22.19 import
yarn
yarn npm audit
```

2023-06-15 18:16 UTC, merceyz requested changes
Excellent, seems like it's not printing all vulnerabilities though.
Ref https://github.com/yarnpkg/berry/issues/3945.

2023-06-15 18:37 UTC, arcanis commented
Turns out the library we use doesn't support multiple tree items with the same label. Fixed 👍

2023-06-15 18:48 UTC, merceyz approved these changes
Perfect, well done!

2023-06-15 20:20 UTC, merceyz commented on packages/plugin-npm-cli/sources/npmAuditUtils.ts
> +    }
I'm a bit worried about this causing a `Maximum call stack size exceeded` error, could you make it iterative instead?

2023-06-16 08:21 UTC, merged

2023-07-04 12:02 UTC, nitinkothwal commented
Hello @arcanis, Do you know in which version this change is likely to be available? We are eagerly waiting for this change as our Github ci tasks which runs yarn audit fails with 400 bad requests. I checked with latest released yarn version 3.6.1 but this change wasn't there. Do you know any temporary workaround that we can use? Thanks!

2023-07-04 12:21 UTC, arcanis commented
Since it's a major change to the implementation, it won't be released in 3.x. You can already use the RCs, though.

2023-07-28 11:42 UTC, naugtur commented
Would selective fixes to issues causing yarn3 to generate invalid input to the audit endpoint be addressed as part of ongoing v3 maintenance then?

2023-08-15 18:26 UTC, philmayfield commented
Agreed, if its broken in v3 (which is current at the time of writing) it seems like a maintenance issue?

2023-08-18 12:32 UTC, ocostello commented
We're on 3.5.1 and are also experiencing it. I'm surprised it's written off as an inclusion to 3.X, seems like a security vulnerability staying on this major version