Adds support for running native binaries without JS intermediaries
yarnpkg/berry pull request #5508
Opened 2023-06-17 19:49 UTC by arcanis

**What's the problem this PR addresses?**

Yarn currently cannot run native binaries without going through a JS jumper script. Other package managers don't have this restriction, and it makes the `yarn run` overhead worse on some scripts for little reasons - or doesn't work at all when packages don't use jumper scripts.

**How did you fix it?**

Two mechanisms are used:

- First we check for the binary extension
- Then we check its magic number

If one of the two match a predetermined list, the binary is spawned without going through Node. This ensures that this logic is called only when the binary is truly a native binary, and will not affect the behaviour of other existing scripts.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2023-06-17 23:23 UTC, merceyz requested changes
Presumably we'll need to do this for the following locations as well:
https://github.com/yarnpkg/berry/blob/ca475757fe85cdc2c4b4441f6d65d38fdab230ad/packages/yarnpkg-core/sources/scriptUtils.ts#L491-L495
https://github.com/yarnpkg/berry/blob/ca475757fe85cdc2c4b4441f6d65d38fdab230ad/packages/yarnpkg-core/sources/scriptUtils.ts#L544-L548
https://github.com/yarnpkg/berry/blob/ca475757fe85cdc2c4b4441f6d65d38fdab230ad/packages/yarnpkg-core/sources/scriptUtils.ts#L741-L745

2023-06-17 23:23 UTC, merceyz commented on packages/plugin-pnp/sources/jsInstallUtils.ts
> +  `.bin`,
Could you add a comment for this extension?

2023-06-19 16:57 UTC, merceyz commented
There are some issues that this probably fixes (for example https://github.com/yarnpkg/berry/issues/882), could you check and link to them so they're closed?

2023-06-20 11:46 UTC, merged

2023-06-29 18:42 UTC, jmatsushita commented
I've tried `yarn set version 4.0.0-rc.47` with `expo@9.0.0-beta.0` in a monorepo but it doesn't fix ti.
```
> yarn workspace client expo info                                                                                                       .../node_modules/expo/bin/cli:3
# Forward all arguments to the local CLI (@expo/cli).
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0
```

2023-06-29 19:06 UTC, arcanis commented
This fix is only about *native binaries*. From your logs, expo is a shellscripts, which aren't allowed in `bin` at the moment for the reasons outlined in https://github.com/yarnpkg/berry/issues/882#issuecomment-1599478009.

2023-07-20 05:02 UTC, MorisR commented
Will the changes be also added to yarn 3? 
we're still stuck on node v16 and yarn 4 requires node v18

2023-07-20 10:51 UTC, merceyz commented
Yes, I've backported it now so it will be in the next release.