fix(plugin-npm-cli): fix login with Verdaccio
yarnpkg/berry pull request #5983
Opened 2023-11-19 01:20 UTC by demurgos

**What's the problem this PR addresses?**

This commit fixes `yarn npm login` when the remote registry is Verdaccio.

- Closes yarnpkg/berry#1044
- Closes verdaccio/verdaccio#1737

...

**How did you fix it?**

When a user already exists, the registry replies with `409 Conflict`. The official npm client then retrieves the latest user state and inserts a revision, using HTTP basic authentication. This step was missing, and this commits adds it.

The change was tested to work with a private Verdaccio registry. It should now be as reliable as the official npm client.

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2023-11-19 01:44 UTC, merceyz requested changes
I find it a bit odd that the `login` command performs user registration, that doesn't seem right.

2023-11-19 02:02 UTC, demurgos commented
Just to clarify, I 100% agree that it's weird, but it's how the npm registry has always worked. [`npm login` is an alias for `npm adduser`](https://docs.npmjs.com/cli/v8/commands/npm-adduser).

I updated my PR to fix typechecking. The PR works and follows the logic of the officiel client, but I'm forcing a basic auth authorization header manually. I could try pushing it to `npmHttpUtls` if needed.

2023-11-19 11:05 UTC, arcanis commented
The diff sounds reasonable to me. I suspect we don't actually support the register flow since we don't send the email, so this would address the "can we avoid doing both" part 🤔

2023-11-19 11:30 UTC, merceyz commented on .yarn/versions/89f35c90.yml
Only need to mark `@yarnpkg/cli` and `@yarnpkg/plugin-npm-cli` for release.

2023-11-19 12:04 UTC, demurgos commented on .yarn/versions/89f35c90.yml
I initially only updated these two packages, but [CI was failing](https://github.com/yarnpkg/berry/actions/runs/6919990382/job/18823968098). I had to add the plugins for CI to be green.

If you want I can revert to only mark `@yarnpkg/cli` and `@yarnpkg/plugin-npm-cli` but CI will probably fail again.

2023-11-19 12:08 UTC, demurgos commented on .yarn/versions/89f35c90.yml
I updated my PR to only updated the two packages (and fix typos in comments). I'm waiting on CI.

2023-11-19 12:21 UTC, demurgos commented on .yarn/versions/89f35c90.yml
It failed due to missing version changes. @merceyz Should I leave the two packages, or mark or all packages depending in `@yarnpkg/cli`?

2023-11-19 13:00 UTC, merceyz commented on .yarn/versions/89f35c90.yml
You need to mark the rest as `declined`.

2023-11-19 13:26 UTC, demurgos commented on .yarn/versions/89f35c90.yml
Thank you for your explanation: it's fixed now

2023-11-28 18:18 UTC, merged

2023-11-28 18:19 UTC, arcanis commented
Thanks for reminding me! I'll look to make a patch release later this week.

2023-11-28 22:39 UTC, demurgos commented
Thank you very much :)

I know that Yarn does regular releases, so don't feel pressured to release just for this fix. Having it on master and knowing that it will be in the next patch is good enough already for me.