Update `@yarnpkg/extensions` for `eslint-import-resolver-vite@<2.0.1`
yarnpkg/berry pull request #6154
Opened 2024-03-06 16:54 UTC by n0099

**What's the problem this PR addresses?**

https://github.com/pzmosquito/eslint-import-resolver-vite/pull/22

**How did you fix it?**

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2024-03-06 18:21 UTC, merceyz requested changes
Yarn, along with the other package managers, ignores `devDependencies` of dependencies so this wont do anything as is.

2024-03-06 18:21 UTC, merceyz commented on packages/yarnpkg-extensions/sources/index.ts
> +    devDependencies: {
```suggestion
  // https://github.com/pzmosquito/eslint-import-resolver-vite/pull/22
  // https://github.com/pzmosquito/eslint-import-resolver-vite/commit/97b8111b03d3f8c66506732ac965e906568e8dc1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
  [`eslint-import-resolver-vite@<2.0.1`, {
    dependencies: {
```

2024-03-06 18:43 UTC, merceyz approved these changes
Thank you

2024-03-06 18:48 UTC, merceyz approved these changes

2024-03-10 09:20 UTC, arcanis approved these changes

2024-03-10 09:21 UTC, merged