chore: replace lodash with es-toolkit
yarnpkg/berry pull request #6502
Opened 2024-09-13 21:38 UTC by wojtekmaj

## What's the problem this PR addresses?

es-toolkit is a modern lodash alternative that claims to be much faster and lighter, potentially improving Yarn overall performance: https://es-toolkit.slash.page/intro.html

## How did you fix it?

The lazy way, frankly: using es-toolkit/compat to provide practically drop-in lodash replacement with minimal effort.

## Checklist

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

2024-09-13 22:09 UTC, merceyz commented
Our dependencies are using `lodash` so this would just increase the install size and maybe the bundle size.

2024-09-14 19:55 UTC, wojtekmaj commented
Valid point, but it seems like not too many dependencies are in fact using lodash. It should be relatively easy to clean this whole tree up. In the meantime, this draft PR is in itself ready to go I believe. :)

2024-09-14 20:57 UTC, wojtekmaj commented
Well, this PR DOES make Yarn smaller by a bit:

Before: 2.62 MiB
https://github.com/yarnpkg/berry/actions/runs/10862544508/job/30145695733#step:6:366

After: 2.6 MiB
![image](https://github.com/user-attachments/assets/f5d2cb91-26ba-4df5-997c-acc6845648a7)

2024-09-14 21:35 UTC, merceyz commented
> while other dependencies like ink are indeed using lodash, they, just like Yarn, are importing modules selectively from it

Because I patched it to do that, in the future we could change that patch to use `es-toolkit` instead.
https://github.com/yarnpkg/berry/blob/fb6d2d696f36040bb082ddd20adffab67eaa59dc/.yarn/patches/ink-npm-3.0.8-3a8005f59f.patch

2024-09-14 21:42 UTC, merceyz requested changes
Please add an entry for `lodash` and `@types/lodash` here: https://github.com/yarnpkg/berry/blob/d5431bd0cc23730328ef8f61eac11c20db2fec3f/yarn.config.cjs#L211

2024-09-14 22:21 UTC, wojtekmaj commented
I couldn't forget @types/lodash because it appears to be deeply rooted inside pkg-tests-specs, but lodash alone was fine :)

2024-09-14 23:50 UTC, merceyz commented on yarn.config.cjs
> +    forbidDependency(ctx, `inquirer`, `Don't depend on inquirer - we use enquirer instead`);
```suggestion
```

2024-12-02 11:16 UTC, wojtekmaj commented
Update: the latest version of ink, our dependency, also switched from lodash to es-toolkit, making this PR more welcome than before, IMO. I'll work in getting my work rebased.

2025-05-10 06:21 UTC, dayongkr commented
I think @wojtekmaj had  addressed all the review comments—any reason the review isn’t proceeding?

Also, since some time has passed, I think it would be good to update the `es-toolkit` version.

2025-07-14 18:03 UTC, RDIL commented
I can re-review if you can fix the conflicts first!

2025-07-15 07:44 UTC, wojtekmaj commented
@RDIL Done! :)

BTW, this PR still does its job, still decreases binary size.

Before: 2.86 MiB
https://github.com/yarnpkg/berry/actions/runs/15427018142/job/43416399142#step:5:27

After: 2.84 MiB
> ➤ YN0000: ✓ Done building the CLI!
> ➤ YN0000: ? Bundle path: /workspaces/berry/packages/yarnpkg-cli/bundles/yarn.js
> ➤ YN0000: ? Bundle size: 2.84 MiB
> ➤ YN0000: ? Bundle version: 4.9.2-git.20241202.hash-693272998

2025-07-26 03:44 UTC, spanishpear commented
@RDIL thank you!! Are we waiting on one more review to merge this? Not sure if it's a stale request or not ❤️

2025-07-26 08:19 UTC, merged