Treat `.mts` as an es module file
yarnpkg/berry pull request #6596
Opened 2024-11-12 18:32 UTC by RDIL

## What's the problem this PR addresses?

Hopefully fixes #6595

## How did you fix it?

Always consider it an es module

## Checklist

- [ ] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [ ] I have set the packages that need to be released for my changes to be effective.

- [ ] I will check that all automated PR checks pass before the PR gets reviewed.

2025-01-20 14:13 UTC, adrian-gierakowski commented
Anything stopping progress on this PR?

2025-01-20 15:35 UTC, RDIL commented
Sorry @adrian-gierakowski, completely forgot to follow up here.

2025-01-20 17:56 UTC, merceyz requested changes
Needs tests.

2025-01-27 11:14 UTC, goloveychuk requested changes

2025-01-27 11:14 UTC, goloveychuk commented on packages/yarnpkg-pnp/sources/esm-loader/loaderFlags.ts
> +export const SUPPORTS_TYPE_STRIPPING = major > 23 || (major === 23 && minor > 6);
to make strip types works, you need to change pnp mjs loader and chain other loaders , because (assumption is) types stripes is implemented as loader also. 
https://github.com/yarnpkg/berry/issues/6595#issuecomment-2545840548

2025-01-27 11:15 UTC, goloveychuk commented on packages/yarnpkg-pnp/sources/esm-loader/loaderFlags.ts
> +export const SUPPORTS_TYPE_STRIPPING = major > 23 || (major === 23 && minor > 6);
test with simple type could written to validates this

2025-04-10 15:58 UTC, goloveychuk commented
@RDIL can we finish this pls?

2025-04-10 17:30 UTC, goloveychuk commented
```
return {
    format,
    source: format === `commonjs` ? void 0 : await fs.promises.readFile(filePath, `utf8`),
    shortCircuit: false
  };
 ```
 should be replaced with `return nextLoad(urlString, context, nextLoad);`
 because typescript types striping is done by loader.
 So, probably, pnp loader should hack fs and  and then just chain other loaders without explicit loading files.
 @arcanis wdyt?

2025-04-10 18:53 UTC, RDIL commented
@goloveychuk sorry, i'm super busy these days, but if you want to grab my commits and make a new PR, I'm happy to review

2025-04-13 04:11 UTC, RDIL commented
Closing in favor of https://github.com/yarnpkg/berry/pull/6763

2025-04-13 04:11 UTC, closed without merging